language: generic
sudo: required
services: 
  -  docker

before_install:
  - docker build -t jpkeisala/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jpkeisala/react-test npm run test -- --coverage

after_success:
  - docker build -t jpkeisala/multi-docker-client ./client
  - docker build -t jpkeisala/multi-docker-nginx ./nginx
  - docker build -t jpkeisala/multi-docker-server ./server
  - docker build -t jpkeisala/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push jpkeisala/multi-docker-client
  - docker push jpkeisala/multi-docker-nginx
  - docker push jpkeisala/multi-docker-server
  - docker push jpkeisala/multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-421066486201"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  access_secret_key:
    secure: $AWS_SECRET_KEY

